import { StyleSheet } from '@react-pdf/renderer'

export const colors = {
  background: '#0F1115',
  panel: '#151922',
  foreground: '#F7F8FA',
  foregroundSecondary: 'rgba(247,248,250,0.72)',
  foregroundMuted: 'rgba(247,248,250,0.5)',
  accent: '#3B82F6',
  accentSecondary: '#8B5CF6',
  success: '#10B981',
  white: '#FFFFFF',
  dark: '#1A1F2B',
}

export const pdfStyles = StyleSheet.create({
  page: {
    padding: 48,
    fontFamily: 'Helvetica',
    fontSize: 11,
    color: '#333333',
    backgroundColor: '#FFFFFF',
  },
  coverPage: {
    padding: 0,
    backgroundColor: colors.background,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  coverTitle: {
    fontSize: 36,
    fontFamily: 'Helvetica-Bold',
    color: colors.foreground,
    textAlign: 'center',
    marginBottom: 12,
    lineHeight: 1.2,
  },
  coverSubtitle: {
    fontSize: 16,
    color: colors.foregroundSecondary,
    textAlign: 'center',
    maxWidth: 400,
    lineHeight: 1.5,
  },
  coverBrand: {
    fontSize: 12,
    color: colors.accent,
    letterSpacing: 2,
    marginTop: 60,
  },
  sectionTitle: {
    fontSize: 22,
    fontFamily: 'Helvetica-Bold',
    color: colors.background,
    marginBottom: 16,
    paddingBottom: 8,
    borderBottomWidth: 2,
    borderBottomColor: colors.accent,
  },
  chapterTitle: {
    fontSize: 18,
    fontFamily: 'Helvetica-Bold',
    color: colors.background,
    marginBottom: 12,
  },
  body: {
    fontSize: 11,
    lineHeight: 1.7,
    color: '#444444',
    marginBottom: 12,
  },
  highlightBox: {
    backgroundColor: '#F0F7FF',
    borderLeftWidth: 3,
    borderLeftColor: colors.accent,
    padding: 12,
    marginVertical: 12,
    borderRadius: 2,
  },
  highlightText: {
    fontSize: 10,
    color: colors.accent,
    lineHeight: 1.5,
  },
  listItem: {
    flexDirection: 'row',
    marginBottom: 6,
    paddingLeft: 4,
  },
  listBullet: {
    width: 16,
    fontSize: 10,
    color: colors.accent,
  },
  listText: {
    flex: 1,
    fontSize: 10,
    lineHeight: 1.5,
    color: '#444444',
  },
  checkItem: {
    flexDirection: 'row',
    marginBottom: 8,
    alignItems: 'flex-start',
  },
  checkBox: {
    width: 14,
    height: 14,
    borderWidth: 1.5,
    borderColor: colors.accent,
    borderRadius: 2,
    marginRight: 10,
    marginTop: 1,
  },
  checkText: {
    flex: 1,
    fontSize: 10,
    lineHeight: 1.5,
    color: '#444444',
  },
  termRow: {
    flexDirection: 'row',
    marginBottom: 8,
    paddingBottom: 8,
    borderBottomWidth: 0.5,
    borderBottomColor: '#E5E7EB',
  },
  term: {
    width: 140,
    fontSize: 10,
    fontFamily: 'Helvetica-Bold',
    color: colors.background,
  },
  definition: {
    flex: 1,
    fontSize: 10,
    color: '#666666',
    lineHeight: 1.4,
  },
  tocItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
    paddingBottom: 6,
    borderBottomWidth: 0.5,
    borderBottomColor: '#E5E7EB',
  },
  tocText: {
    fontSize: 12,
    color: '#333333',
  },
  ctaBox: {
    backgroundColor: colors.background,
    padding: 32,
    borderRadius: 8,
    marginTop: 24,
    alignItems: 'center',
  },
  ctaTitle: {
    fontSize: 18,
    fontFamily: 'Helvetica-Bold',
    color: colors.foreground,
    marginBottom: 8,
    textAlign: 'center',
  },
  ctaText: {
    fontSize: 11,
    color: colors.foregroundSecondary,
    textAlign: 'center',
    lineHeight: 1.6,
    marginBottom: 16,
  },
  ctaButton: {
    backgroundColor: colors.accent,
    paddingVertical: 10,
    paddingHorizontal: 24,
    borderRadius: 6,
  },
  ctaButtonText: {
    fontSize: 12,
    fontFamily: 'Helvetica-Bold',
    color: colors.white,
  },
  pageNumber: {
    position: 'absolute',
    bottom: 24,
    right: 48,
    fontSize: 9,
    color: '#999999',
  },
})
